## how to convert image color using cv2.cvtcolor ?

In [1]:
import numpy as np 
import cv2

img=cv2.imread('images/luffy1.jpg')
img=cv2.resize(img,(1280,720))

cv2.imshow("image",img)
cv2.waitKey(0)
cv2.destroyAllWindows()

qt.qpa.plugin: Could not find the Qt platform plugin "wayland" in "/home/bikash/anaconda3/lib/python3.9/site-packages/cv2/qt/plugins"
Qt: Session management error: Could not open network socket


In [2]:
# shape of the image
img.shape

(720, 1280, 3)

In [3]:
# blue color matrix
img[:,:,0]

array([[192, 191, 192, ...,   1,   1,   1],
       [192, 191, 192, ...,   1,   1,   1],
       [192, 191, 192, ...,   1,   1,   1],
       ...,
       [ 23,  23,  23, ...,  82,  82,  82],
       [ 23,  23,  23, ...,  82,  82,  82],
       [ 23,  23,  23, ...,  84,  84,  84]], dtype=uint8)

In [4]:
# green color matrix
img[:,:,1]

array([[183, 182, 183, ...,   1,   1,   1],
       [183, 182, 183, ...,   1,   1,   1],
       [183, 182, 183, ...,   1,   1,   1],
       ...,
       [ 20,  20,  20, ...,  87,  87,  87],
       [ 20,  20,  20, ...,  87,  87,  87],
       [ 20,  20,  20, ...,  89,  89,  89]], dtype=uint8)

In [5]:
# red color matrix
img[:,:,2]

array([[180, 179, 180, ...,   1,   1,   1],
       [180, 179, 180, ...,   1,   1,   1],
       [180, 179, 180, ...,   1,   1,   1],
       ...,
       [ 42,  42,  42, ...,  90,  90,  90],
       [ 42,  42,  42, ...,  90,  90,  90],
       [ 42,  42,  42, ...,  92,  92,  92]], dtype=uint8)

In [1]:
# converting the image  from bgr into rgb
import numpy as np 
import cv2

img=cv2.imread('images/luffy1.jpg')
img=cv2.resize(img,(1280,720))
img_rgb=cv2.cvtColor(img,cv2.COLOR_BGR2RGB)

cv2.imshow("image in rgb",img_rgb)
cv2.waitKey(0)
cv2.destroyAllWindows()

qt.qpa.plugin: Could not find the Qt platform plugin "wayland" in "/home/bikash/anaconda3/lib/python3.9/site-packages/cv2/qt/plugins"
Qt: Session management error: Could not open network socket


In [7]:
# converting the image from bgr to gray
import numpy as np 
import cv2

img=cv2.imread('images/luffy1.jpg')
img=cv2.resize(img,(1280,720))
img_gray=cv2.cvtColor(img,cv2.COLOR_BGR2GRAY)

cv2.imshow("image",img_gray)
cv2.waitKey(0)
cv2.destroyAllWindows()

In [1]:
# converting the original image to all color format

import numpy as np
import cv2

img=cv2.imread('images/luffy1.jpg')
img_res=cv2.resize(img,(1280,720))
img_color=[cv2.COLOR_BAYER_BG2BGR,cv2.COLOR_BAYER_BG2BGR_EA,cv2.COLOR_BAYER_BG2BGR_VNG,cv2.COLOR_BAYER_BG2BGRA,
cv2.COLOR_BAYER_BG2GRAY,cv2.COLOR_BAYER_BG2RGB,cv2.COLOR_BAYER_BG2RGB_EA,cv2.COLOR_BAYER_BG2RGB_VNG,
cv2.COLOR_YUV420sp2BGRA]
img_color

for color in img_color:
    print(color)
    
    color_img=cv2.cvtColor(img_res,color)
    cv2.imshow(f"image in {color} ",color_img)
    cv2.waitKey(0)
    cv2.destroyAllWindows()

46


error: OpenCV(4.6.0) /io/opencv/modules/imgproc/src/demosaicing.cpp:1721: error: (-215:Assertion failed) scn == 1 && (dcn == 3 || dcn == 4) in function 'demosaicing'
