## How to split image in single channel and merge multiple single channel

In [1]:
import numpy as np 
import cv2

img=cv2.imread('images/luffy1.jpg')
img=cv2.resize(img,(1280,720))

cv2.imshow("image",img)
cv2.waitKey(0)
cv2.destroyAllWindows()

qt.qpa.plugin: Could not find the Qt platform plugin "wayland" in "/home/bikash/anaconda3/lib/python3.9/site-packages/cv2/qt/plugins"
Qt: Session management error: Could not open network socket


In [2]:
# split image using numpy indexing
img

array([[[192, 183, 180],
        [191, 182, 179],
        [192, 183, 180],
        ...,
        [  1,   1,   1],
        [  1,   1,   1],
        [  1,   1,   1]],

       [[192, 183, 180],
        [191, 182, 179],
        [192, 183, 180],
        ...,
        [  1,   1,   1],
        [  1,   1,   1],
        [  1,   1,   1]],

       [[192, 183, 180],
        [191, 182, 179],
        [192, 183, 180],
        ...,
        [  1,   1,   1],
        [  1,   1,   1],
        [  1,   1,   1]],

       ...,

       [[ 23,  20,  42],
        [ 23,  20,  42],
        [ 23,  20,  42],
        ...,
        [ 82,  87,  90],
        [ 82,  87,  90],
        [ 82,  87,  90]],

       [[ 23,  20,  42],
        [ 23,  20,  42],
        [ 23,  20,  42],
        ...,
        [ 82,  87,  90],
        [ 82,  87,  90],
        [ 82,  87,  90]],

       [[ 23,  20,  42],
        [ 23,  20,  42],
        [ 23,  20,  42],
        ...,
        [ 84,  89,  92],
        [ 84,  89,  92],
        [ 84,  89,  92]]

In [3]:
img.shape

(720, 1280, 3)

In [4]:
# intensity of blue color
img[:,:,0]

array([[192, 191, 192, ...,   1,   1,   1],
       [192, 191, 192, ...,   1,   1,   1],
       [192, 191, 192, ...,   1,   1,   1],
       ...,
       [ 23,  23,  23, ...,  82,  82,  82],
       [ 23,  23,  23, ...,  82,  82,  82],
       [ 23,  23,  23, ...,  84,  84,  84]], dtype=uint8)

In [5]:
# intensity of green color
img[:,:,1]

array([[183, 182, 183, ...,   1,   1,   1],
       [183, 182, 183, ...,   1,   1,   1],
       [183, 182, 183, ...,   1,   1,   1],
       ...,
       [ 20,  20,  20, ...,  87,  87,  87],
       [ 20,  20,  20, ...,  87,  87,  87],
       [ 20,  20,  20, ...,  89,  89,  89]], dtype=uint8)

In [6]:
# intensity of red color
img[:,:,2]

array([[180, 179, 180, ...,   1,   1,   1],
       [180, 179, 180, ...,   1,   1,   1],
       [180, 179, 180, ...,   1,   1,   1],
       ...,
       [ 42,  42,  42, ...,  90,  90,  90],
       [ 42,  42,  42, ...,  90,  90,  90],
       [ 42,  42,  42, ...,  92,  92,  92]], dtype=uint8)

## splitting image using cv2.split()

In [7]:
b,g,r=cv2.split(img)

# showing image in blue channel

In [8]:
import numpy as np 
import cv2

img=cv2.imread('images/luffy1.jpg')
img=cv2.resize(img,(1280,720))

cv2.imshow("image",img[:,:,0])
cv2.waitKey(0)
cv2.destroyAllWindows()

## showing image in green channel


In [9]:
import numpy as np 
import cv2

img=cv2.imread('images/luffy1.jpg')
img=cv2.resize(img,(1280,720))

cv2.imshow("image",img[:,:,1])
cv2.waitKey(0)
cv2.destroyAllWindows()

## showing image into red channel]


In [10]:
import numpy as np 
import cv2

img=cv2.imread('images/luffy1.jpg')
img=cv2.resize(img,(1280,720))

cv2.imshow("image",img[:,:,2])
cv2.waitKey(0)
cv2.destroyAllWindows()

In [12]:
import numpy as np 
import cv2

img=cv2.imread('images/luffy1.jpg')
img=cv2.resize(img,(1280,720))

cv2.imshow("blue channel",img[:,:,0])
cv2.imshow("greenchannel",img[:,:,1])
cv2.imshow("red channel",img[:,:,2])
cv2.waitKey(0)
cv2.destroyAllWindows()

In [ ]:
# spliiting and then merging the image
import numpy as np 
import cv2

img=cv2.imread('images/luffy1.jpg')
img=cv2.resize(img,(400,400))

b,g,r=cv2.split(img)
img_merge=cv2.merge([b,g,r])

cv2.imshow("blue channel",b)
cv2.imshow("greenchannel",g)
cv2.imshow("red channel",r)
cv2.imshow("bgr channel merged image",img_merge)
cv2.waitKey(0)
cv2.destroyAllWindows()