### how to access image pixel and modify

In [2]:
import numpy as np
import cv2

ali=cv2.imread('images/alisha.jpg')
cv2.imshow("image",ali)
cv2.waitKey(0)
cv2.destroyAllWindows()

qt.qpa.plugin: Could not find the Qt platform plugin "wayland" in "/home/bikash/anaconda3/lib/python3.9/site-packages/cv2/qt/plugins"


In [3]:
ali.shape

(1080, 1080, 3)

### Access single pixel of image

In [4]:
ali[0,0]

array([39, 27, 23], dtype=uint8)

In [5]:
ali[512,400]

array([133, 137, 166], dtype=uint8)

In [6]:
ali[1000,10]

array([233, 129, 124], dtype=uint8)

In [7]:
ali[450,450]

array([ 78,  51, 155], dtype=uint8)

In [8]:
ali[700,300]

array([34, 24, 70], dtype=uint8)

In [9]:
ali[100,500]

array([ 95,  88, 149], dtype=uint8)

In [10]:
ali[200:,500]

array([125, 114, 154], dtype=uint8)

### how to show single pixel

In [16]:
cv2.imshow("pixel single",ali[512,300])
cv2.waitKey(0)
cv2.destroyAllWindows()

### Accessing the row of image

In [57]:
# first method accesing the row at index 5
ali[5]

array([[39, 27, 23],
       [39, 27, 23],
       [39, 27, 23],
       ...,
       [53, 35, 34],
       [50, 32, 31],
       [52, 34, 33]], dtype=uint8)

In [58]:
# second method
ali[5,:]

array([[39, 27, 23],
       [39, 27, 23],
       [39, 27, 23],
       ...,
       [53, 35, 34],
       [50, 32, 31],
       [52, 34, 33]], dtype=uint8)

In [21]:
ali[950,:]

array([[136,  26,  22],
       [149,  39,  35],
       [120,  10,   6],
       ...,
       [ 39,  27,  23],
       [ 39,  27,  23],
       [ 39,  27,  23]], dtype=uint8)

### accessing the row of single or double channel

In [23]:
# accessing the row and single channel
ali[950,:,2]

array([22, 35,  6, ..., 23, 23, 23], dtype=uint8)

In [25]:
# accessing the row of double channel
ali[1000,:,(0,1,2)]

array([[179, 138, 144, ...,  39,  39,  39],
       [ 62,  21,  29, ...,  27,  27,  27],
       [ 59,  18,  26, ...,  23,  23,  23]], dtype=uint8)

In [32]:
cv2.imshow("dfa",ali[:,:,(1,0,2)])
cv2.waitKey(0)
cv2.destroyAllWindows()

### Access the column of image

In [33]:
# accessing the column at 0th index
ali[:,0]

array([[ 39,  27,  23],
       [ 39,  27,  23],
       [ 39,  27,  23],
       ...,
       [182,  72,  66],
       [150,  40,  34],
       [157,  47,  41]], dtype=uint8)

In [34]:
# accessing the column at 200th index
ali[:,200]

array([[ 39,  27,  23],
       [ 39,  27,  23],
       [ 39,  27,  23],
       ...,
       [155,  45,  41],
       [173,  63,  59],
       [168,  58,  54]], dtype=uint8)

### accessing the column and channel 


In [37]:
# accessing the column at 500th indes and channel 0 ,1
ali[:,500,(0,1)]

array([[ 55,  38],
       [ 54,  39],
       [ 53,  38],
       ...,
       [153,  40],
       [172,  59],
       [156,  43]], dtype=uint8)

### Accessing the part of image


In [39]:
# accesint the image after 2ooth index row wise and 5ooth wise column
cv2.imshow("accessing after 500th col and 200th row",ali[500:,200:])
cv2.waitKey(0)
cv2.destroyAllWindows()

In [47]:
cv2.imshow('accessing face',ali[0:600,0:1000])
cv2.imwrite('faceex.jpg',ali[0:600,0:1000])
cv2.waitKey(0)
cv2.destroyAllWindows()

In [50]:
ali[0].shape

(1080, 3)

## showing image rowwise

In [51]:
for i in range(ali.shape[0]):
    cv2.imshow("image",ali[0:i+1,:])
    
    if cv2.waitKey(27) & 0xFF==ord('q'):
        break
cv2.destroyAllWindows()

### showing image columnwise


In [54]:
for j in range(ali.shape[0]):
    cv2.imshow("image",ali[:,0:j+1])

    if cv2.waitKey(27) & 0xFF==ord("q"):
        break

cv2.destroyAllWindows()